language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../3817061_Lembrikov_All_labs
  - make -j
  - cd ./Vector/Vector
  - cd ./VectorTest/VectorTest
  - cd ./Matrix/Matrix
  - cd ./MatrixTest/MatrixTest
notifications:
  email: false