language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../3817061_Lembrikov_All_labs
  - make -j
  - ./VectorTest/VectorTest
  - ./MatrixTest/MatrixTest
  - ./StackTest/StackTest
  - ./QueueTest/QueueTest
  - ./ListTest/ListTest
notifications:
  email: false